spring.application.name=file_management_system

spring.datasource.driver-class-name=org.postgresql.Driver
#Linux\u30b5\u30fc\u30d0\u30fc\u4f7f\u7528\u6642\u30b3\u30e1\u30f3\u30c8\u30a2\u30a6\u30c8\u3092\u5916\u3059
#spring.datasource.url=jdbc:postgresql://192.168.2.98:5432/file_management_system
#Windows\u30b5\u30fc\u30d0\u30fc\u4f7f\u7528\u6642\u30b3\u30e1\u30f3\u30c8\u30a2\u30a6\u30c8\u3092\u5916\u3059
spring.datasource.url=jdbc:postgresql://192.168.2.230:5432/file_management_system
spring.datasource.username=justinuser
spring.datasource.password=Justin001

spring.messages.basename=messages_ja

spring.devtools.restart.exclude=static/**,public/**,resources/**,META-INF/**,*.jar,*.war

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# \u30c7\u30d5\u30a9\u30eb\u30c8\u306e\u30a8\u30e9\u30fc\u30da\u30fc\u30b8\u3092\u7121\u52b9\u5316
server.error.whitelabel.enabled=false

# \u30a8\u30e9\u30fc\u30da\u30fc\u30b8\u306e\u30d1\u30b9\u3092\u6307\u5b9a\u3059\u308b\uff08\u30ed\u30b0\u30a4\u30f3\u753b\u9762\u3078\u306e\u9077\u79fb\u8a2d\u5b9a\uff09
server.error.path=/login/login
