spring.application.name=file_management_system

spring.datasource.driver-class-name=org.postgresql.Driver
#Linuxサーバー使用時コメントアウトを外す
spring.datasource.url=jdbc:postgresql://192.168.2.98:5432/file_management_system
#Windowsサーバー使用時コメントアウトを外す
#spring.datasource.url=jdbc:postgresql://192.168.2.230:5432/file_management_system
spring.datasource.username=justinuser
spring.datasource.password=Justin001

spring.jackson.time-zone=Asia/Tokyo

spring.messages.basename=messages_ja

spring.devtools.restart.exclude=static/**,public/**,resources/**,META-INF/**,*.jar,*.war

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# デフォルトのエラーページを無効化
server.error.whitelabel.enabled=false

# エラーページのパスを指定する（ログイン画面への遷移設定）
server.error.path=/login/login

# SQL接続時のidle状態を制限(最大接続数:3 タイムアウト:5分)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000